# Generated by Django 4.0.2 on 2022-04-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_HTML', models.TextField(blank=True)),
                ('code_CSS', models.TextField(blank=True)),
                ('code_JS', models.TextField(blank=True)),
                ('isPublic', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('eMail', models.EmailField(editable=False, max_length=320)),
                ('avatarURL', models.URLField(blank=True, max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminated', models.BooleanField(default=False)),
                ('codeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen.code')),
                ('likerFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen.user')),
            ],
        ),
        migrations.AddField(
            model_name='code',
            name='userFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pen.user'),
        ),
    ]
