# Generated by Django 4.0.2 on 2022-05-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='likesCount',
            field=models.IntegerField(default=0),
        ),
    ]
