# Generated by Django 4.0.2 on 2022-05-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='projectURL',
        ),
    ]
