# Generated by Django 4.0.2 on 2022-05-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pen', '0002_remove_code_projecturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_CSS',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_HTML',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_JS',
            field=models.TextField(blank=True, default=''),
        ),
    ]
